stages:
  - deploy

default:
  image: node:20

Deploy Review:
  stage: deploy
  script:
    - echo "Deploying in Netlify"
    - echo "URL = https://deploy-preview-<nth preview deploy>--remix-template.netlify.app"
  only:
    - branches
  except:
    - staging
    - master
  tags:
    - chateau

Deploy Staging:
  stage: deploy
  script:
    - echo "Deploying staging in Netlify"
    - echo "URL = https://staging--remix-template.netlify.app"
  only:
    - staging
  tags:
    - chateau

Deploy Production:
  stage: deploy
  script:
    - echo "Deploying in Netlify"
    - echo "URL = https://remix-template.netlify.app/"
  only:
    - master
  tags:
    - chateau
# works but the gitlab/netlify integration works too and is faster
# Deploy Review:
#   stage: deploy
#   script:
#     - npm i
#     - npm i -g netlify-cli
#     - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --build --debug
#   environment:
#     name: review/$CI_COMMIT_REF_SLUG
#     url: https://$CI_COMMIT_REF_SLUG--$NETLIFY_DOMAIN.netlify.app
#   only:
#     - branches
#   except:
#     - staging
#     - master
#   tags:
#     - chateau

# Deploy Staging:
#   stage: deploy
#   script:
#     - npm i
#     - npm i -g netlify-cli
#     - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --build
#   environment:
#     name: staging
#     url: https://staging-$NETLIFY_DOMAIN.netlify.app
#   only:
#     - staging
#   tags:
#     - chateau

# Deploy Production:
#   stage: deploy
#   script:
#     - npm i
#     - npm i -g netlify-cli
#     - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --build --prod
#   environment:
#     name: production
#     url: https://$NETLIFY_DOMAIN.netlify.app
#   only:
#     - master
#   tags:
#     - chateau
